import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Eye, MapPin, MessageCircle } from "lucide-react";

export const metadata: Metadata = { title: "À propos", description: "L’approche MyLombok : une conciergerie locale, lisible et humaine pour préparer un séjour à Lombok." };

export default function AboutPage() {
  return <main className="inner-page about-page"><header className="about-hero"><div className="about-hero__image"><Image src="/lombok-bay.jpg" alt="Paysage côtier de Lombok entre palmiers, route et baie" fill priority sizes="100vw" /></div><div className="site-container about-hero__copy"><span className="eyebrow eyebrow--light">Notre manière de vous accompagner</span><h1>Proche du terrain.<br />Loin du bruit.</h1><p>MyLombok est né d’une idée simple : faciliter les choix pratiques sans prendre la place du voyageur.</p></div></header><section className="site-section"><div className="site-container editorial-grid"><div><span className="eyebrow">Notre rôle</span><h2>Rendre votre séjour plus lisible.</h2></div><div className="home-intro__copy"><p className="lead-copy">Nous ne sommes ni un hôtel, ni une plateforme de réservation généraliste.</p><p>MyLombok est un point de contact local. L’application vous aide à explorer ; la conciergerie vous aide à formuler et organiser une demande lorsque vous souhaitez gagner du temps ou être accompagné.</p></div></div></section><section className="site-section about-values"><div className="site-container"><article><MapPin aria-hidden="true" /><h2>Centré sur Lombok</h2><p>L’exploration détaillée reste volontairement limitée à l’île et à ses voisines proches.</p></article><article><Eye aria-hidden="true" /><h2>Transparent sur les limites</h2><p>Une information non vérifiée est présentée comme « à confirmer » plutôt que transformée en certitude.</p></article><article><MessageCircle aria-hidden="true" /><h2>Une conversation humaine</h2><p>Les demandes passent par WhatsApp afin que vous puissiez relire et valider chaque message.</p></article></div></section><section className="site-section final-cta-section"><div className="site-container final-cta"><span className="eyebrow eyebrow--light">Votre projet</span><h2>Préparons la suite ensemble.</h2><p>Commencez par nous dire ce que vous souhaitez simplifier.</p><Link className="button button--light" href="/conciergerie">Parler à MyLombok <ArrowRight aria-hidden="true" /></Link></div></section></main>;
}
